FROM php:8.1-cli

RUN apt-get update && apt-get install -y \
    libzip-dev \
    && docker-php-ext-install zip mysqli pdo pdo_mysql

WORKDIR /var/www/html

COPY . .

EXPOSE 8080

CMD ["php", "-S", "0.0.0.0:8080"]
